#!/bin/bash

CURRENT=$(git branch --show-current)

if [ "$CURRENT" = "main" ]; then
  git pull origin main && git checkout -b "$POULPE_BRANCH_NAME"
else
  git fetch origin main:main && git checkout -b "$POULPE_BRANCH_NAME" main
fi
